import Head from "next/head";

import React, { useState } from "react";
import { ClipLoader } from "react-spinners";
import randomWords from "random-words";

import BookCard from "../components/BookCard";
import styles from "../styles/Home.module.css";

export default function Home() {
  const [search, setSearch] = useState("");
  const [books, setBooks] = useState([]);
  const [randomWd, setRandomWd] = useState("");

  const [loading, setLoading] = useState(false);

  // setting search value randomly
  const getFunBooks = () => {
    let random = randomWords();
    setRandomWd(random);
    getBooks(random);
    setSearch("");
  };

  // fetching the books
  const getBooks = async (search) => {
    if (search.length) {
      setLoading(true);
      const res = await fetch(`/api/getBook?book=${search}`);
      const data = await res.json();
      setBooks(data.items);

      setSearch("");
      setTimeout(() => {
        setLoading(false);
      }, 2000);
    }
  };

  return (
    <>
      <Head>
        <title>2Books</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
      </Head>

      <main>
        <div className={styles.home}>
          <div className={styles.titleName}>
            2Bo<span className={styles.colText}>oks</span>
          </div>

          <input
            type="text"
            className={styles.searchBar}
            value={search}
            onChange={(e) => setSearch(e.target.value)}
            placeholder="Give me a book..."
          />
          <div className={styles.btnGroup}>
            <button
              className={styles.searchBtn}
              onClick={() => getBooks(search)}
            >
              Find books
            </button>
            <button className={styles.funBtn} onClick={getFunBooks}>
              Fun search
            </button>
          </div>
        </div>
        <div>
          {loading ? (
            <div className={styles.loader}>
              <ClipLoader />
            </div>
          ) : (
            <BookCard books={books} />
          )}
        </div>
      </main>
    </>
  );
}
